### ISSUE TITLE
docker-compose: pass configuration to hawkbit-update-server

### ISSUE THREAD

**Issue by lab-w** [eclipse/hawkbit#1062]
I'm using docker-compose to run my hawkbit server. Here the section in my .yml file:
```
  hawkbit:
    image: "hawkbit/hawkbit-update-server:latest-mysql"
    ports:
    - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
    environment:
    - 'SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hawkbit'
    - 'SPRING_DATASOURCE_USERNAME=root'
    - 'SPRING_DATASOURCE_PASSWORD=example'
    - 'SPRING_RABBITMQ_HOST=rabbitmq'
    - 'SPRING_RABBITMQ_USERNAME=guest'
    - 'SPRING_RABBITMQ_PASSWORD=guest'
```
I have configured the MySQL and RabbitMQ login details. Is it possible to configure further system parameters in a simmilar manner? I'm especially interested in setting the option "Allow a gateway to authenticate and manage multiple targets through a gateway security token" and in setting this token.
Is there a list of available parameters?
Thanks for your support!
