### ISSUE TITLE
Hawkbit redirects to http, breaking SSL-Termination with Proxy

### ISSUE THREAD

**Issue by bauerstefan** [eclipse/hawkbit#1724]
Hi,
my setup is simple:

Client -> =https = > NGINX (hawkbit.domain) -> =http= http://192.168.0.1:8080

Now curling from client-side shows:

```
$ curl -v https://hawkbit.domain/
*   Trying 1.2.3.4:443...
* Connected to hawkbit.domain (1.2.3.4) port 443 (#0)
*  SSL certificate verify ok.

> GET / HTTP/2
> Host: hawkbit.domain
> user-agent: curl/7.81.0

< location: http://hawkbit.domain/swagger-ui/index.html;jsessionid=16B76......?
```

Howto force hawkbit to **not** send http redirects? Maybe this is also a job for nginx?

I tried 

```
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mariadb://mysql-hawkbit:3306/hawkbit",
        "spring.rabbitmq.host": "rabbitmq",
        "spring.rabbitmq.username": "guest",
        "spring.rabbitmq.password": "guest",
        "spring.datasource.username": "root",
        "hawkbit.server.security.require-ssl": "true",
        "server.use-forward-headers": "true"
       }'
```
with no success.

Accessing https://hawkbit.local/swagger-ui/index.html directly **works** without redirects.

any help is greatly appreciated.

**Comment by mwiesenbauer** [comment]
try:
```yaml
environment:
  SPRING_APPLICATION_JSON: '{
    "spring.datasource.url": "jdbc:mariadb://mysql-hawkbit:3306/hawkbit",
    "spring.rabbitmq.host": "rabbitmq",
    "spring.rabbitmq.username": "guest",
    "spring.rabbitmq.password": "guest",
    "spring.datasource.username": "root",
    "hawkbit.server.security.require-ssl": true,
    "server.forward-headers-strategy": "FRAMEWORK"
   }'
```
for details: https://github.com/eclipse/hawkbit/issues/1696#issuecomment-2075302680
