### ISSUE TITLE
Artifact failure:  Failed to retrieve element from array for path $._links.download-http.href"

### ISSUE THREAD

**Issue by dHARIZ-25** [eclipse/hawkbit#1843]
Hello,
I am having issues with hawkbit... I am using this current configuration in docker compose:
```yaml
        ...
        "hawkbit.artifact.url.protocols.download-http.rel":"https",
        "hawkbit.artifact.url.protocols.download-http.protocol": "https",
        "hawkbit.artifact.url.protocols.download-http.port": "443",
        "hawkbit.server.forward-headers-strategy":"NATIVE",
        "hawkbit.artifact.url.protocols.download-http.hostname": "hostname.cloud",
        "hawkbit.artifact.url.protocols.download-http.ref": "{protocol}://{hostnameRequest}:{port}/{tenant}/controller/v1/{controllerId}/softwaremodules/{softwareModuleId}/artifacts/{artifactFileName}"}'
 volumes:
      - artifactrepo:/artifactrepo
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    labels:
      NAME: "hawkbit"

volumes:
  artifactrepo:
    driver: local
```
hawkbit works but whenever I assign a DS to my RAUC client I get this (debug logging activated)
```shell
MESSAGE: Checking for new software...
DEBUG: Response body: {
  "config" : {
    "polling" : {
      "sleep" : "00:05:00"
    }
  },
  "_links" : {
    "deploymentBase" : {
      "href" : "http://hostname.cloud/DEFAULT/controller/v1/board-025334000026/deploymentBase/239?c=631397877"
    },
    "installedBase" : {
      "href" : "http://hostname.cloud/DEFAULT/controller/v1/board-025334000026/installedBase/151"
    }
  }
}
DEBUG: Response body: {
  "id" : "239",
  "deployment" : {
    "download" : "forced",
    "update" : "skip",
    "chunks" : [
      {
        "part" : "os",
        "version" : "0.36.12",
        "name" : "SM_0.36.12",
        "artifacts" : [
          {
            "filename" : "lorch-bundle-dev-stm32mp1-mapro.raucb",
            "hashes" : {
              "sha1" : "8d59a177d14a313e22f4d8c5550e4d12700575fe",
              "md5" : "52b3e2ef26f5b971676a7529cc291591",
              "sha256" : "9735eb844ce62a46b82ea38443c2c77e410139c0ae813e6046649580465ee41e"
            },
            "size" : 112048101,
            "_links" : {
              "https" : {
                "href" : "https://hostname.cloud:443/DEFAULT/controller/v1/board-025334000026/softwaremodules/19/artifacts/lorch-bundle-dev-stm32mp1-mapro.raucb"
              },
              "md5sum-http" : {
                "href" : "https://hoastname.cloud:443/DEFAULT/controller/v1/board-025334000026/softwaremodules/19/artifacts/lorch-bundle-dev-stm32mp1-mapro.raucb.MD5SUM"
              }
            }
          }
        ]
      }
    ]
  }
}
MESSAGE: hawkBit requested to skip installation, not invoking RAUC yet.
```
the software module 19 exists in mysql
![image](https://github.com/user-attachments/assets/46d2f81e-e19a-4e9a-be45-4221c3c3e369)

where does the SM get stored in the container? this is the output of artifactrepo on my container:
![image](https://github.com/user-attachments/assets/d0b26b39-8c42-4561-94fd-f80426446b9a)

I tried creating new SM and then new DS but still same error.
what could be the solution?
