### ISSUE TITLE
Custom application.properties on Kubernetes and max upload size.

### ISSUE THREAD

**Issue by mprzygrodzki** [eclipse/hawkbit#803]
Hello,

I'm facing an issue with setting custome application.properties to work with Hawkbit Update Server. My Hawkbit deployment is running as docker image on Kubernetes from official repo. Everything was fine till I have to add some bigger artifact files. I've found already that by default the file size is limited to 1Mb. 

I know i need to set some custom values in application.properties file to extend the limits. What i have done:
- created custom application.properties file which contains following entries:
    multipart.maxFileSize=1073741824
    multipart.maxRequestSize=1073741824

I've placed this file into /opt/hawkbit/data directory which i believe is the home directory for Hawkbit. But I still cannot upload bigger files. I'm confused how to work with this this file or maybe i need to somehow force hawkbit to use this file at startup , or maybe to file location is wrong ? Please help.

**Comment by schabdo** [comment]
Glad to hear that you're using hawkBit in a Kubernetes setup. Indeed SpringBoot will pick up the mounted `application.properties` from same directory.

However I think the properties you're looking for are rather `spring.servlet.multipart.max-file-size` and `spring.servlet.multipart.max-request-size` ([cf. MultipartProperties](https://github.com/spring-projects/spring-boot/blob/v2.1.3.RELEASE/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/MultipartProperties.java#L64))

Please let me know if this resolves your issue.

**Comment by mprzygrodzki** [comment]
@schabdo - thank you for your reply. I believe the issue is solved right now, but there was some other thing which was blocking upload --> behind my LB theres Nginx-Ingress controller which by default allows uploads which maximum size is 1mb. Updating ingress for Hawkbit with special annotation resolved my issues. Properties are various and related to the Spring version, in my case is 1.4 so my setting should be fine.

**Comment by damontheimpulsive** [comment]
@schabdo :  I am also facing the same issue for bigger files.  I am running through docker container in AWS and i have added custom application.properties file in the hawkbit. There i have addd below property : 

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

But still it is not taking bigger files of more than 1 GB. Any suggestions

**Comment by schabdo** [comment]
Have you tried to set `hawkbit.server.security.dos.maxArtifactSize` to a higher value as well (cf. [HawkbitSecurityProperties](https://github.com/eclipse/hawkbit/blob/master/hawkbit-security-core/src/main/java/org/eclipse/hawkbit/security/HawkbitSecurityProperties.java#L267))?

**Comment by damontheimpulsive** [comment]
It worked finally

**Comment by damontheimpulsive** [comment]
spring.servlet.multipart.max-file-size=${MAX_ARTIFACT_SIZE:1073741824}
spring.servlet.multipart.max-request-size=${MAX_ARTIFACT_SIZE:1073741824}
hawkbit.server.security.dos.maxArtifactSize=${MAX_ARTIFACT_SIZE:1073741824}

I have set above 3 values in my app.properties file. Worked for me

**Comment by paltaa** [comment]
Im still trying to make this work in kubernetes, can anyone provide a working config? Some example of the helm values that do not work:

```
config:
  application:
    # hawkbit.server.security.dos.maxArtifactSize: "1073741824"
    # hawkbit.server.security.dos.maxArtifactStorage: "10737418240"
    # spring.servlet.multipart.max-file-size: "1073741824"
    # spring.servlet.multipart.max-request-size: "1073741824"
    hawkbit:
      # multipart.maxFileSize: "1073741824"
      # multipart.maxRequestSize: "1073741824"
      multipart:
        maxFileSize: "1073741824"
        maxRequestSize: "1073741824"
      server:
        useForwardHeaders: true
        security:
          dos:
            maxArtifactSize: "1073741824"
            maxArtifactStorage: "10737418240"
      #     oidc-client-id: "[KEYCLOAK_DEVICE_REGISTRY_CLIENT_ID]"
    spring:
      servlet:
        multipart:
          enabled: "true"
          max-file-size: "1073741824"
          max-request-size: "1073741824"
```
