### ISSUE TITLE
Why stop uaa extension?

### ISSUE THREAD

**Issue by wendaotao** [eclipse/hawkbit#809]
Hi, developers, why stop uaa extension. I think it is a strong feature request.

**Comment by schabdo** [comment]
Indeed it is a nice feature and hawkBit still lacks multi-user support. So let me shed some light on it how we came to that conclusion:   

Supporting and maintaining the extension over time became an issue since nobody on the team is really using the extension nor has knowledge about UAA. Finally during Spring Boot 2 migration the question arised what needs to be done, how we migrate and test the extension and guarantee that everything is working properly. So we decided to not migrate the UAA extension. 

Hope this helps to understand why we stopped it.

**Comment by sbabic** [comment]
Hi Dominic,

On 18/03/19 19:17, Dominic Schabel wrote:
> Indeed it is a nice feature and hawkBit still lacks multi-user support.
> So let me shed some light on it how we came to that conclusion:
> 
> Supporting and maintaining the extension over time became an issue since
> nobody on the team is really using the extension nor has knowledge about
> UAA. Finally during Spring Boot 2 migration the question arised what
> needs to be done, how we migrate and test the extension and guarantee
> that everything is working properly. So we decided to not migrate the
> UAA extension.
> 
> Hope this helps to understand why we stopped it.

These are all good points. Anyway, I just ask:

- is there some plan to add multi-user / multi-tenant support to Hawkbit ?

- if you get patches for uaa could they (if they pass your review of
course) be merged or do you have different plans for it, maybe without uaa ?

Thanks,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by stschake** [comment]
If all you need is multiple, statically configured users (possibly with different permissions), we have an extension for that that we could contribute to the extensions repo. This still means basic authentication, so in practice you want to have some other form of isolation for the management interface in place.

**Comment by schabdo** [comment]
@stschake that sounds awesome, thanks a lot! If this is the case I'd support your initiative. As far as I know there are currently no other plans for multi-user support. I don't know any details of your extension but maybe we could even replace the existing implementation of the [UserDetailsService](https://github.com/eclipse/hawkbit/blob/master/hawkbit-autoconfigure/src/main/java/org/eclipse/hawkbit/autoconfigure/security/InMemoryUserManagementAutoConfiguration.java#L59), continue the use of `spring.security.user` as default user (with all permissions) and introduce new statically configured users optionally. What do you guys think?

**Comment by stschake** [comment]
@schabdo I've submitted https://github.com/eclipse/hawkbit-extensions/pull/43

**Comment by schabdo** [comment]
Cool, thanks! As promised I'll have a closer look at it...

**Comment by schabdo** [comment]
@wendaotao @sbabic support for statically configured users is heading towards master (https://github.com/eclipse/hawkbit/pull/829). Hope this helps.

**Comment by subhadippramanik** [comment]
I already have achieved multi user and multi tenancy on 0.2.1 using application.yml
It looks like
```yaml
tenant:
  users:
    - name: ${USER:admin}
      password: ${PASSWORD:admin}
      tenant: DEFAULT
      grants:
        - ALL
    - name: ${USER1:user1}
      password: ${USER1_PASSWORD:somepassword}
      tenant: DEFAULT
      grants:
        - READ_TARGET
        - UPDATE_TARGET
        - READ_REPOSITORY
        - UPDATE_REPOSITORY
        - CREATE_REPOSITORY
        - DELETE_REPOSITORY
    - name: ${EXT_USER:user2}
      password: ${EXT_PASSWORD:somepassword}
      tenant: EXTERNAL
      grants:
        - CREATE_TARGET
        - READ_TARGET
        - READ_TARGET_SEC_TOKEN
        - UPDATE_TARGET
        - DELETE_TARGET
        - READ_REPOSITORY
        - UPDATE_REPOSITORY
        - CREATE_REPOSITORY
        - DELETE_REPOSITORY
```
